version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: company_management
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: --auth
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
